### ISSUE TITLE
Curl Error on server

### ISSUE THREAD

**Issue by himanshutecstub** [angelleye/paypal-php-library#112]
I use this code for send PayPal Invoice in website.
It's working fine but i got 'Hostname was NOT found in DNS cache' error from server every time.
In server install curl version :- 7.35.0

**Comment by angelleye** [comment]
It seems to be working fine from our test server, although you'll see a failure because of the duplicate invoice ID:  http://paypal.angelleye.com/paypal-php-library/samples/CreateAndSendInvoice.php

It sounds like you've got some sort of a DNS issue going on with your server.  Can you try switching to Google DNS or Open DNS or something like that?

**Comment by himanshutecstub** [comment]
Thanks,
Is there any curl setting require for PHP or server to resolve this?
Can you describe how i send PayPal invoice using Google DNS?

**Comment by angelleye** [comment]
The DNS servers that your server is using would need to be updated.  You won't be able to do this unless you're working on a dedicated server of your own.  What you may need to do is submit a ticket with your hosting provider letting them know about the DNS error you're getting but that it's not happening from other servers and see what they say.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PPCL-91
