### ISSUE TITLE
Can we still use this library as PayPal has deprecated the NVP Express checkout methods.

### ISSUE THREAD

**Issue by vikramsingh86** [angelleye/paypal-php-library#114]
In the source code of this library I found that its still using NVP format for sending the request. As per PayPal documentation, it is deprecated now. 
Can we still use this library for reference transaction. Please suggest.

**Comment by angelleye** [comment]
Yes, you can still use this.  They are starting label these as deprecated because they are trying to get people into the REST API.  There are way too many people using it, though, so they are not going away.  Also, the REST API does not offer everything the Classic (NVP/SOAP) API provides, so for some things you simply cannot use REST yet.  

I still personally use the NVP APIs and will be for quite some time.  We do have REST built into our library now, and that will all be included in the next update we release, but we haven't been able to focus on it lately because we have other more popular tools (like our WordPress/WooCommerce plugins) that are keeping us busy.  

Again, though, you can use this worry free.  The NVP API isn't going anywhere.
