### ISSUE TITLE
Angell Eye PayPal SDK ssl error connection

### ISSUE THREAD

**Issue by llihund19** [angelleye/paypal-php-library#64]
Since Paypal updated their security, Angell eye always return ssl error connection. I don't know what the problem is. Why is it always returning ssl error connection. What do I need to do? And where is the problem? From the Angell Eye SDK or from the web server? Thank in advance

**Comment by angelleye** [comment]
I'm assuming you are referring to the sslv3 handshake failure..??  This is a server environment problem.

You need to make sure your server supports sending HTTP requests via the TLS protocol instead of SSLv3.  This is because of the [POODLE Vulnerability](https://en.wikipedia.org/wiki/POODLE).  Pretty much everybody made this change, not just PayPal.

The easiest thing to do is contact your hosting provider and let them know you're running into this error, so you need the web server software updated to fix the problem.  Specifically, OpenSSL.
