### ISSUE TITLE
DECP + RP

### ISSUE THREAD

**Issue by keyurptl** [angelleye/paypal-php-library#76]
Do Express Checkout Payment + Recurring Payment

**Comment by keyurptl** [comment]
created from #75

**Comment by angelleye** [comment]
Lots of adjustments needed here similar to what I did in #75.

**Comment by tejasm-itpath** [comment]
> Starts with a single item at $50.00 and ends with multiple items at different amounts.
Reason behind above mentioned problem is , We have stored everything in Session and while running multiple demos together it cause sometimes because we have same session variable name in every demo,
I have tested this and it's working perfect, May be you need only verbiage correction and description adding only. 
@angelleye

**Comment by angelleye** [comment]
At the end of any demo, though, we're destroying the session data so it should start fresh again each time around.  I will run more tests on this and see.
