### ISSUE TITLE
Index Page of the demo directory need to be same as CI demos.

### ISSUE THREAD

**Issue by keyurptl** [angelleye/paypal-php-library#77]

**Comment by keyurptl** [comment]
Created this issue from Issue-76

**Comment by angelleye** [comment]
At this point we have a Demo button and a Download Code button, and we logic around the download code button so it either lets them download or displays a buy now link.  This isn't really what we need, though.  If the code is found, then there is no readon to download it because they already have it.  

Really what we need here is to Display a single button that will either load the demo kit or say Buy Now depending on whether or not that particular demo kit is installed.
