### ISSUE TITLE
How to pass Custom propertie ?

### ISSUE THREAD

**Issue by SvetoslavStefanov** [angelleye/paypal-php-library#95]
Hello,
I'm using this library to make the payment and paypal's IPN to notify my script about successfully placed payments.
The problem is that I'm not able to pass a _custom_ field, so that I can get it with Paypal's notifications.
I'm using paypal-php-library/samples/Pay.php to make the payment. I've tried to add the custom property to $PayRequestFields, but without any success.

With this simulater - https://developer.paypal.com/developer/ipnSimulator/ - there is a filed _custom_ and when I fill it, it comes with Paypal's notification. How can I make the same thing with Pay.php ?

ps: I know it's described very confusing, I'm just very tired, I'm trying to do this thing for hours ...

**Comment by angelleye** [comment]
The Pay API works on PayPal's Adaptive Payments platform, and it does not support a "custom" parameter directly.  You can add a call to SetPaymentOptions to include some additional details, but it still doesn't include a specific "custom" parameter.  Instead, you could pass an invoice ID, for example, and store any custom data you need in your local DB so that it can be pulled back out using that invoice ID.  Hope that helps!

**Comment by SvetoslavStefanov** [comment]
Yeah, the InvoiceID works for me. Thanks !
